-- MySQL Script generated by MySQL Workbench
-- 05/07/18 00:06:41
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema pm
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pm
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pm` DEFAULT CHARACTER SET utf8 ;
USE `pm` ;

-- -----------------------------------------------------
-- Table `pm`.`contato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pm`.`contato` (
  `idContato` INT(11) NOT NULL AUTO_INCREMENT,
  `telefone` VARCHAR(25) NULL DEFAULT NULL,
  `celular` VARCHAR(25) NULL DEFAULT NULL,
  `hangouts` VARCHAR(100) NULL DEFAULT NULL,
  `skype` VARCHAR(100) NULL DEFAULT NULL,
  `github` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`idContato`))
ENGINE = InnoDB
AUTO_INCREMENT = 31
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pm`.`conta_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pm`.`conta_usuario` (
  `idContaUsuario` INT(11) NOT NULL AUTO_INCREMENT,
  `idContato` INT(11) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `senha` VARCHAR(500) NOT NULL,
  `nomeUsuario` VARCHAR(100) NULL DEFAULT NULL,
  `tipoUsuario` VARCHAR(3) NULL DEFAULT NULL,
  `tipoPessoa` VARCHAR(3) NULL DEFAULT NULL,
  `dataNascimento` DATE NULL DEFAULT NULL,
  `cpf_cnpj` VARCHAR(80) NULL DEFAULT NULL,
  PRIMARY KEY (`idContaUsuario`),
  INDEX `fk_conta_usuario_contato1_idx` (`idContato` ASC),
  CONSTRAINT `fk_conta_usuario_contato1`
    FOREIGN KEY (`idContato`)
    REFERENCES `pm`.`contato` (`idContato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 23
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pm`.`dados_educacionais_desenvolvedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pm`.`dados_educacionais_desenvolvedor` (
  `idDadosEducacionaisDesenvolvedor` INT(11) NOT NULL AUTO_INCREMENT,
  `idContaUsuario` INT(11) NOT NULL,
  `matricula` VARCHAR(50) NOT NULL,
  `instituicaoEnsino` VARCHAR(100) NOT NULL,
  `curso` VARCHAR(150) NOT NULL,
  `turno` VARCHAR(12) NOT NULL,
  `periodo` INT(11) NOT NULL,
  `declaracaoMatricula` LONGBLOB NOT NULL,
  PRIMARY KEY (`idDadosEducacionaisDesenvolvedor`),
  INDEX `fk_dados_educacionais_desenvolvedor_conta_usuario1_idx` (`idContaUsuario` ASC),
  CONSTRAINT `fk_dados_educacionais_desenvolvedor_conta_usuario1`
    FOREIGN KEY (`idContaUsuario`)
    REFERENCES `pm`.`conta_usuario` (`idContaUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pm`.`dados_educacionais_tutor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pm`.`dados_educacionais_tutor` (
  `idDadosEducacionaisTutor` INT(11) NOT NULL AUTO_INCREMENT,
  `idContaUsuario` INT(11) NOT NULL,
  `siape` VARCHAR(15) NOT NULL,
  `instituicaoEnsino` VARCHAR(100) NOT NULL,
  `formacaoAcademica` VARCHAR(100) NOT NULL,
  `cargo` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idDadosEducacionaisTutor`),
  INDEX `fk_dados_educacionais_tutor_conta_usuario1_idx` (`idContaUsuario` ASC),
  CONSTRAINT `fk_dados_educacionais_tutor_conta_usuario1`
    FOREIGN KEY (`idContaUsuario`)
    REFERENCES `pm`.`conta_usuario` (`idContaUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pm`.`equipe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pm`.`equipe` (
  `idEquipe` INT(11) NOT NULL,
  `nomeEquipe` VARCHAR(100) NOT NULL,
  `descricao` VARCHAR(150) NULL DEFAULT NULL,
  `idProjeto` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`idEquipe`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pm`.`membrosequipe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pm`.`membrosequipe` (
  `idMembrosEquipe` INT(11) NOT NULL AUTO_INCREMENT,
  `conta_usuario_idContaUsuario` INT(11) NOT NULL,
  `equipe_idEquipe` INT(11) NOT NULL,
  PRIMARY KEY (`idMembrosEquipe`),
  INDEX `fk_conta_usuario_has_equipe_equipe1_idx` (`equipe_idEquipe` ASC),
  INDEX `fk_conta_usuario_has_equipe_conta_usuario1_idx` (`conta_usuario_idContaUsuario` ASC),
  CONSTRAINT `fk_conta_usuario_has_equipe_conta_usuario1`
    FOREIGN KEY (`conta_usuario_idContaUsuario`)
    REFERENCES `pm`.`conta_usuario` (`idContaUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_conta_usuario_has_equipe_equipe1`
    FOREIGN KEY (`equipe_idEquipe`)
    REFERENCES `pm`.`equipe` (`idEquipe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pm`.`projeto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pm`.`projeto` (
  `idProjeto` INT(11) NOT NULL AUTO_INCREMENT,
  `idContaUsuario` INT(11) NOT NULL,
  `nomeProjeto` VARCHAR(200) NULL DEFAULT NULL,
  `areaAtuacao` VARCHAR(100) NULL DEFAULT NULL,
  `descricao` VARCHAR(1000) NULL DEFAULT NULL,
  `finalidade` VARCHAR(1000) NULL DEFAULT NULL,
  `mobile` INT(11) NULL DEFAULT '0',
  `web` INT(11) NULL DEFAULT '0',
  `desktop` INT(11) NULL DEFAULT '0',
  PRIMARY KEY (`idProjeto`),
  INDEX `fk_projeto_conta_usuario1_idx` (`idContaUsuario` ASC),
  CONSTRAINT `fk_projeto_conta_usuario1`
    FOREIGN KEY (`idContaUsuario`)
    REFERENCES `pm`.`conta_usuario` (`idContaUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
