-- MySQL Script generated by MySQL Workbench
-- Sat May  5 16:54:47 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema pm
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pm
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pm` DEFAULT CHARACTER SET utf8 ;
USE `pm` ;

-- -----------------------------------------------------
-- Table `pm`.`contato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pm`.`contato` (
  `idContato` INT NOT NULL AUTO_INCREMENT,
  `telefone` VARCHAR(25) NULL,
  `celular` VARCHAR(25) NULL,
  `hangouts` VARCHAR(100) NULL,
  `skype` VARCHAR(100) NULL,
  `github` VARCHAR(100) NULL,
  PRIMARY KEY (`idContato`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pm`.`conta_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pm`.`conta_usuario` (
  `idContaUsuario` INT NOT NULL AUTO_INCREMENT,
  `idContato` INT NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `senha` VARCHAR(500) NOT NULL,
  `nomeUsuario` VARCHAR(100) NULL,
  `tipoUsuario` VARCHAR(3) NULL,
  `tipoPessoa` VARCHAR(3) NULL,
  `dataNascimento` DATE NULL,
  PRIMARY KEY (`idContaUsuario`),
  INDEX `fk_conta_usuario_contato1_idx` (`idContato` ASC),
  CONSTRAINT `fk_conta_usuario_contato1`
    FOREIGN KEY (`idContato`)
    REFERENCES `pm`.`contato` (`idContato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pm`.`dados_educacionais_desenvolvedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pm`.`dados_educacionais_desenvolvedor` (
  `idDadosEducacionaisDesenvolvedor` INT NOT NULL AUTO_INCREMENT,
  `idContaUsuario` INT NOT NULL,
  `matricula` VARCHAR(50) NOT NULL,
  `instituicaoEnsino` VARCHAR(100) NOT NULL,
  `curso` VARCHAR(150) NOT NULL,
  `turno` VARCHAR(12) NOT NULL,
  `periodo` INT NOT NULL,
  `declaracaoMatricula` LONGBLOB NOT NULL,
  PRIMARY KEY (`idDadosEducacionaisDesenvolvedor`),
  INDEX `fk_dados_educacionais_desenvolvedor_conta_usuario1_idx` (`idContaUsuario` ASC),
  CONSTRAINT `fk_dados_educacionais_desenvolvedor_conta_usuario1`
    FOREIGN KEY (`idContaUsuario`)
    REFERENCES `pm`.`conta_usuario` (`idContaUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pm`.`dados_educacionais_tutor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pm`.`dados_educacionais_tutor` (
  `idDadosEducacionaisTutor` INT NOT NULL,
  `idContaUsuario` INT NOT NULL,
  `siape` VARCHAR(15) NOT NULL,
  `instituicaoEnsino` VARCHAR(100) NOT NULL,
  `formacaoAcademica` VARCHAR(100) NOT NULL,
  `cargo` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idDadosEducacionaisTutor`),
  INDEX `fk_dados_educacionais_tutor_conta_usuario1_idx` (`idContaUsuario` ASC),
  CONSTRAINT `fk_dados_educacionais_tutor_conta_usuario1`
    FOREIGN KEY (`idContaUsuario`)
    REFERENCES `pm`.`conta_usuario` (`idContaUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pm`.`equipe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pm`.`equipe` (
  `idEquipe` INT NOT NULL,
  `nomeEquipe` VARCHAR(100) NOT NULL,
  `descricao` VARCHAR(150) NULL,
  `idProjeto` VARCHAR(100) NULL,
  PRIMARY KEY (`idEquipe`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pm`.`membrosEquipe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pm`.`membrosEquipe` (
  `idMembrosEquipe` INT NOT NULL AUTO_INCREMENT,
  `conta_usuario_idContaUsuario` INT NOT NULL,
  `equipe_idEquipe` INT NOT NULL,
  INDEX `fk_conta_usuario_has_equipe_equipe1_idx` (`equipe_idEquipe` ASC),
  INDEX `fk_conta_usuario_has_equipe_conta_usuario1_idx` (`conta_usuario_idContaUsuario` ASC),
  PRIMARY KEY (`idMembrosEquipe`),
  CONSTRAINT `fk_conta_usuario_has_equipe_conta_usuario1`
    FOREIGN KEY (`conta_usuario_idContaUsuario`)
    REFERENCES `pm`.`conta_usuario` (`idContaUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_conta_usuario_has_equipe_equipe1`
    FOREIGN KEY (`equipe_idEquipe`)
    REFERENCES `pm`.`equipe` (`idEquipe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pm`.`plataforma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pm`.`plataforma` (
  `idPlataforma` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idPlataforma`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pm`.`projeto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pm`.`projeto` (
  `idProjeto` INT NOT NULL AUTO_INCREMENT,
  `idPlataforma` INT NOT NULL,
  `idContaUsuario` INT NOT NULL,
  `nomeProjeto` VARCHAR(200) NULL,
  `areaAtuacao` VARCHAR(100) NULL,
  `descricao` VARCHAR(1000) NULL,
  `finalidade` VARCHAR(1000) NULL,
  PRIMARY KEY (`idProjeto`),
  INDEX `fk_projeto_plataforma1_idx` (`idPlataforma` ASC),
  INDEX `fk_projeto_conta_usuario1_idx` (`idContaUsuario` ASC),
  CONSTRAINT `fk_projeto_plataforma1`
    FOREIGN KEY (`idPlataforma`)
    REFERENCES `pm`.`plataforma` (`idPlataforma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_projeto_conta_usuario1`
    FOREIGN KEY (`idContaUsuario`)
    REFERENCES `pm`.`conta_usuario` (`idContaUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pm`.``
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pm`.`` (
  `idSistema` INT NOT NULL AUTO_INCREMENT,
  `col` VARCHAR(45) NULL,
  PRIMARY KEY (`idSistema`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
