-- MySQL Script generated by MySQL Workbench
-- 04/29/18 09:15:36
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema pm
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pm
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pm` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `pm` ;

-- -----------------------------------------------------
-- Table `pm`.`contato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pm`.`contato` (
  `idContato` INT NOT NULL AUTO_INCREMENT,
  `telefone` VARCHAR(25) NULL,
  `celular` VARCHAR(25) NULL,
  `hangouts` VARCHAR(100) NULL,
  `skype` VARCHAR(100) NULL,
  `github` VARCHAR(100) NULL,
  PRIMARY KEY (`idContato`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pm`.`conta_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pm`.`conta_usuario` (
  `idContaUsuario` INT NOT NULL AUTO_INCREMENT,
  `idContato` INT NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `senha` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`idContaUsuario`),
  INDEX `fk_conta_usuario_contato1_idx` (`idContato` ASC),
  CONSTRAINT `fk_conta_usuario_contato1`
    FOREIGN KEY (`idContato`)
    REFERENCES `pm`.`contato` (`idContato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pm`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pm`.`cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `idContaUsuario` INT NOT NULL,
  `nomeCliente` VARCHAR(100) NOT NULL,
  `telefone` VARCHAR(25) NULL,
  `celular` VARCHAR(25) NULL,
  `hangouts` VARCHAR(100) NULL,
  `skype` VARCHAR(100) NULL,
  PRIMARY KEY (`idCliente`),
  INDEX `fk_cliente_conta_usuario1_idx` (`idContaUsuario` ASC),
  CONSTRAINT `fk_cliente_conta_usuario1`
    FOREIGN KEY (`idContaUsuario`)
    REFERENCES `pm`.`conta_usuario` (`idContaUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pm`.`pessoa_fisica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pm`.`pessoa_fisica` (
  `idPessoaFisica` INT NOT NULL AUTO_INCREMENT,
  `idCliente` INT NOT NULL,
  `cpf` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPessoaFisica`),
  INDEX `fk_pessoa_fisica_cliente_idx` (`idCliente` ASC),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC),
  CONSTRAINT `fk_pessoa_fisica_cliente`
    FOREIGN KEY (`idCliente`)
    REFERENCES `pm`.`cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pm`.`pessoa_juridica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pm`.`pessoa_juridica` (
  `idPessoaJuridica` INT NOT NULL AUTO_INCREMENT,
  `idCliente` INT NOT NULL,
  `cnpj` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`idPessoaJuridica`),
  INDEX `fk_pessoa_juridica_cliente1_idx` (`idCliente` ASC),
  UNIQUE INDEX `cnpj_UNIQUE` (`cnpj` ASC),
  CONSTRAINT `fk_pessoa_juridica_cliente1`
    FOREIGN KEY (`idCliente`)
    REFERENCES `pm`.`cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pm`.`desenvolvedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pm`.`desenvolvedor` (
  `idDesenvolvedor` INT NOT NULL AUTO_INCREMENT,
  `idContaUsuario` INT NOT NULL,
  `cpf` VARCHAR(45) NOT NULL,
  `nomeDesenvolvedor` VARCHAR(100) NOT NULL,
  `dataNascimento` DATE NOT NULL,
  PRIMARY KEY (`idDesenvolvedor`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC),
  INDEX `fk_desenvolvedor_conta_usuario1_idx` (`idContaUsuario` ASC),
  CONSTRAINT `fk_desenvolvedor_conta_usuario1`
    FOREIGN KEY (`idContaUsuario`)
    REFERENCES `pm`.`conta_usuario` (`idContaUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pm`.`dados_educacionais_desenvolvedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pm`.`dados_educacionais_desenvolvedor` (
  `idDadosEducacionaisDesenvolvedor` INT NOT NULL AUTO_INCREMENT,
  `idDesenvolvedor` INT NOT NULL,
  `matricula` VARCHAR(50) NOT NULL,
  `instituicaoEnsino` VARCHAR(100) NOT NULL,
  `curso` VARCHAR(150) NOT NULL,
  `turno` VARCHAR(12) NOT NULL,
  `periodo` INT NOT NULL,
  `declaracaoMatricula` LONGBLOB NOT NULL,
  PRIMARY KEY (`idDadosEducacionaisDesenvolvedor`),
  INDEX `fk_dados_educacionais_desenvolvedor1_idx` (`idDesenvolvedor` ASC),
  CONSTRAINT `fk_dados_educacionais_desenvolvedor1`
    FOREIGN KEY (`idDesenvolvedor`)
    REFERENCES `pm`.`desenvolvedor` (`idDesenvolvedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pm`.`tutor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pm`.`tutor` (
  `idTutor` INT NOT NULL AUTO_INCREMENT,
  `idContaUsuario` INT NOT NULL,
  `cpf` VARCHAR(45) NOT NULL,
  `nomeTutor` VARCHAR(100) NOT NULL,
  `dataNascimento` DATE NOT NULL,
  PRIMARY KEY (`idTutor`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC),
  INDEX `fk_tutor_conta_usuario1_idx` (`idContaUsuario` ASC),
  CONSTRAINT `fk_tutor_conta_usuario1`
    FOREIGN KEY (`idContaUsuario`)
    REFERENCES `pm`.`conta_usuario` (`idContaUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pm`.`dados_educacionais_tutor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pm`.`dados_educacionais_tutor` (
  `idDadosEducacionaisTutor` INT NOT NULL AUTO_INCREMENT,
  `idTutor` INT NOT NULL,
  `siape` VARCHAR(15) NOT NULL,
  `instituicaoEnsino` VARCHAR(100) NOT NULL,
  `formacaoAcademica` VARCHAR(100) NOT NULL,
  `cargo` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idDadosEducacionaisTutor`),
  INDEX `fk_dados_educacionais_tutor_tutor1_idx` (`idTutor` ASC),
  CONSTRAINT `fk_dados_educacionais_tutor_tutor1`
    FOREIGN KEY (`idTutor`)
    REFERENCES `pm`.`tutor` (`idTutor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pm`.`equipe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pm`.`equipe` (
  `idEquipe` INT NOT NULL AUTO_INCREMENT,
  `nomeEquipe` VARCHAR(100) NOT NULL,
  `descricao` VARCHAR(150) NULL,
  PRIMARY KEY (`idEquipe`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pm`.`membrosEquipe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pm`.`membrosEquipe` (
  `idMembrosEquipe` INT NOT NULL AUTO_INCREMENT,
  `conta_usuario_idContaUsuario` INT NOT NULL,
  `equipe_idEquipe` INT NOT NULL,
  INDEX `fk_conta_usuario_has_equipe_equipe1_idx` (`equipe_idEquipe` ASC),
  INDEX `fk_conta_usuario_has_equipe_conta_usuario1_idx` (`conta_usuario_idContaUsuario` ASC),
  PRIMARY KEY (`idMembrosEquipe`),
  CONSTRAINT `fk_conta_usuario_has_equipe_conta_usuario1`
    FOREIGN KEY (`conta_usuario_idContaUsuario`)
    REFERENCES `pm`.`conta_usuario` (`idContaUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_conta_usuario_has_equipe_equipe1`
    FOREIGN KEY (`equipe_idEquipe`)
    REFERENCES `pm`.`equipe` (`idEquipe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pm`.`plataforma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pm`.`plataforma` (
  `idPlataforma` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idPlataforma`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pm`.`projeto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pm`.`projeto` (
  `idProjeto` INT NOT NULL AUTO_INCREMENT,
  `idPlataforma` INT NOT NULL,
  `equipe_idEquipe` INT NULL,
  `nomeProjeto` VARCHAR(200) NULL,
  `areaAtuacao` VARCHAR(100) NULL,
  `descricao` VARCHAR(1000) NULL,
  `finalidade` VARCHAR(1000) NULL,
  PRIMARY KEY (`idProjeto`),
  INDEX `fk_projeto_plataforma1_idx` (`idPlataforma` ASC),
  INDEX `fk_projeto_equipe1_idx` (`equipe_idEquipe` ASC),
  CONSTRAINT `fk_projeto_plataforma1`
    FOREIGN KEY (`idPlataforma`)
    REFERENCES `pm`.`plataforma` (`idPlataforma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_projeto_equipe1`
    FOREIGN KEY (`equipe_idEquipe`)
    REFERENCES `pm`.`equipe` (`idEquipe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
